name: Parallel Test Build
on: push
jobs:
  Add-To-Cart-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            command: npm run test:AddToCart

      - name: Cypress Test Report
        uses: actions/upload-artifact@v4
        with:
                  name: mochawesome HTML report-AddToCart
                  path: cypress/reports/html  # or path/to/artifact      
  Reg-Flow-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            command: npm run test:RegistrationPage 
            
      - name: Cypress Test Report
        uses: actions/upload-artifact@v4
        with:
                  name: mochawesome HTML report-RegistrationPage
                  path: cypress/reports/html  # or path/to/artifact            